# Welcome to Jekyll!
title: Design Conversations
email: mail@designconversations.com
description: Dialogues with eminent Australian designers
url: https://designconversations.net
locale: en-AU
lang: en-AU
logo: /assets/images/site/site-logo-dc.png
date_format: "%B %-d, %Y"
markdown: kramdown
incremental: true
skin: "/assets/css/skins/light.css"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Volkhov"
    weights: "400,400i,700,700i"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
  - .claude/
  - .devcontainer/
  - .idea/
  - .ruby-lsp/
  - .sass-cache/
  - src/
  - tmp/
footer_links:
  - title: Apple
    url: https://podcasts.apple.com/au/podcast/design-conversations/id1591996555
    icon: fa fa-podcast
  - title: Feed
    url: atom.xml
    icon: fas fa-rss
  - title: Twitter
    url: https://twitter.com/designconv
    icon: fab fa-twitter fa-2x
  - title: Facebook
    url: https://facebook.com/designconversations
    icon: fab fa-facebook fa-2x
  - title: Instagram
    url: https://www.instagram.com/designconversations/
    icon: fab fa-instagram fa-2x
copyright: >
  [![Creative Commons License](https://licensebuttons.net/l/by-nc-nd/4.0/88x31.png)](https://creativecommons.org/licenses/by-nc-nd/4.0/)<br />
  Except where [otherwise noted](/about/#credits), content on this site is licensed under a<br />
  [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](https://creativecommons.org/licenses/by-nc-nd/4.0/).<br />
  [Privacy Policy](/privacy/)
permalink: /:categories/:year/:title/
feed:
  path: atom.xml
liquid:
  error_mode: strict
sass:
  sass_dir: _sass
twitter:
  username: designconv
author:
  name: Geoff Fitzpatrick
  picture: assets/images/site/author_geoff_fitzpatrick.jpg
  email: mail@designconversations.net
  twitter: designconv
# Production build settings
theme: jekyll-theme-so-simple
remote_theme: ~
# Podcast-specific settings
podcast:
  copyright: >
    Except where otherwise noted, content is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives
    4.0 International License.
  description: >
    <p>Design Conversations is a podcast series aimed at recording an oral history of designers and design practices in
    Australia, from the twentieth century to the present day.</p>
    <p>Each episode is a one-on-one conversation with an eminent design practitioner, in which they detail and elaborate
    on their careers. The series strives to cover most of the design disciplines currently practiced, and examine the
    motivation, inspiration and hard work that brought recognition.</p>
  itunes:
    author: Geoff Fitzpatrick
    owner:
      name: Geoff Fitzpatrick
      email: mail@designconversations.net
    type: episodic
    image: "assets/images/site/site-logo-dc-itunes.png"
    category: Arts
    subcategory: Design
    explicit: "false"
